### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by chlorophant** [nilsramsperger/docker-counterstrike-source-dedicated#1]
I'm able to build the image fine, but when I go to run it I get the following output:

`Installation done
Loading config
Starting CS:S Dedicated Server
Auto detecting CPU
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.
Setting breakpad minidump AppID = 232330
Using breakpad crash handler
dlopen failed trying to load:
/home/steam/.steam/sdk32/steamclient.so
with error:
/home/steam/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Assert( Assertion Failed: CApplicationManager::GetMountVolume: invalid index ):/home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp:3126

Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20200602055915_5.dmp
success = no
error:  libcurl.so: cannot open shared object file: No such file or directory
Setting breakpad minidump AppID = 240
dlopen failed trying to load:
/home/steam/.steam/sdk32/steamclient.so
with error:
/home/steam/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 232330`

Any idea what the issue is?

**Comment by nilsramsperger** [comment]
The server should work, despite the errors. I have those in my log as well.
I am trying to root them out on other Source server projects of mine, and didn't bring the fixes back here. I just pushed a few updates. Some errors are gone, some persist. Please try again.

If you happen to find further fixes, feel free to share your insights. :)

Greets
Nils

**Comment by chlorophant** [comment]
This is my current output:

Installation done
Loading config
Starting CS:S Dedicated Server
Auto detecting CPU
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.
Setting breakpad minidump AppID = 232330
Using breakpad crash handler
dlopen failed trying to load:
/home/steam/.steam/sdk32/steamclient.so
with error:
/home/steam/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Assert( Assertion Failed: CApplicationManager::GetMountVolume: invalid index ):/home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp:3126

Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20200603005300_5.dmp
success = no
error:  libcurl.so: cannot open shared object file: No such file or directory
Setting breakpad minidump AppID = 240
dlopen failed trying to load:
/home/steam/.steam/sdk32/steamclient.so
with error:
/home/steam/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 232330

You are saying this is normal and that the server is actually running correctly? This my first time trying to run a CSS server, I guess I expected more useful output!

I was unable to connect to it with a locally running instance of CSS. Maybe I need to expose the port..

If I run this container locally, should the server be available on the steam server list?

**Comment by nilsramsperger** [comment]
The log output teils me, that your image was not built with the latest version of the code. The „steamclient.so“ error is gone in my environment.

When starting/creating the container, you need to set the -p parameters for local port exposition. 
I suggest, to use the precompiled image from DockerHub (nilsramsperger/counterstrike-source-dedicated) and set it up by the details in the project‘s readme. 

If you want to access the local server from the internet, you will have to do additional port forwarding configurations on your router.

Actually I never checked, if a server set up with this docker image will show up on the global CS:S server list. I just added my instance to the favorites  by IP address. There it stays and can be selected/accessed later.

**Comment by nilsramsperger** [comment]
Since there are no further posts here. I close the issue.
